AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda REST API with IAM Authentication

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: API Gateway deployment stage

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Architectures:
      - x86_64

Resources:
  # API Gateway with IAM Authentication
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: AWS_IAM
        InvokeRole: NONE

  # Lambda Function for API Handler
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main
      Runtime: provided.al2
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: makefile

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  ApiId:
    Description: "API Gateway ID"
    Value: !Ref RestApi
    Export:
      Name: !Sub "${AWS::StackName}-ApiId"

  CurlCommand:
    Description: "Example curl command with AWS SigV4"
    Value: !Sub |
      curl --aws-sigv4 'aws:amz:${AWS::Region}:execute-api' \
           --user 'AWS_ACCESS_KEY_ID:AWS_SECRET_ACCESS_KEY' \
           'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/health'
